export interface Country {
  name: string;
  code: string; // ISO 3166-1 alpha-2
  dialCode: string; // Código telefônico internacional
  flag: string; // Emoji da bandeira
}

// Lista de países mais comuns, priorizando Brasil no topo
export const countries: Country[] = [
  { name: 'Brasil', code: 'BR', dialCode: '55', flag: '🇧🇷' },
  { name: 'Afeganistão', code: 'AF', dialCode: '93', flag: '🇦🇫' },
  { name: 'Ilhas Åland', code: 'AX', dialCode: '358', flag: '🇦🇽' },
  { name: 'Albânia', code: 'AL', dialCode: '355', flag: '🇦🇱' },
  { name: 'Argélia', code: 'DZ', dialCode: '213', flag: '🇩🇿' },
  { name: 'Samoa Americana', code: 'AS', dialCode: '1', flag: '🇦🇸' },
  { name: 'Andorra', code: 'AD', dialCode: '376', flag: '🇦🇩' },
  { name: 'Angola', code: 'AO', dialCode: '244', flag: '🇦🇴' },
  { name: 'Anguilla', code: 'AI', dialCode: '1', flag: '🇦🇮' },
  { name: 'Antígua e Barbuda', code: 'AG', dialCode: '1', flag: '🇦🇬' },
  { name: 'Argentina', code: 'AR', dialCode: '54', flag: '🇦🇷' },
  { name: 'Armênia', code: 'AM', dialCode: '374', flag: '🇦🇲' },
  { name: 'Aruba', code: 'AW', dialCode: '297', flag: '🇦🇼' },
  { name: 'Austrália', code: 'AU', dialCode: '61', flag: '🇦🇺' },
  { name: 'Áustria', code: 'AT', dialCode: '43', flag: '🇦🇹' },
  { name: 'Azerbaijão', code: 'AZ', dialCode: '994', flag: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', dialCode: '1', flag: '🇧🇸' },
  { name: 'Bahrein', code: 'BH', dialCode: '973', flag: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', dialCode: '880', flag: '🇧🇩' },
  { name: 'Barbados', code: 'BB', dialCode: '1', flag: '🇧🇧' },
  { name: 'Bielorrússia', code: 'BY', dialCode: '375', flag: '🇧🇾' },
  { name: 'Bélgica', code: 'BE', dialCode: '32', flag: '🇧🇪' },
  { name: 'Belize', code: 'BZ', dialCode: '501', flag: '🇧🇿' },
  { name: 'Benin', code: 'BJ', dialCode: '229', flag: '🇧🇯' },
  { name: 'Bermudas', code: 'BM', dialCode: '1', flag: '🇧🇲' },
  { name: 'Butão', code: 'BT', dialCode: '975', flag: '🇧🇹' },
  { name: 'Bolívia', code: 'BO', dialCode: '591', flag: '🇧🇴' },
  { name: 'Bonaire', code: 'BQ', dialCode: '599', flag: '🇧🇶' },
  { name: 'Bósnia e Herzegovina', code: 'BA', dialCode: '387', flag: '🇧🇦' },
  { name: 'Botswana', code: 'BW', dialCode: '267', flag: '🇧🇼' },
  { name: 'Ilha Bouvet', code: 'BV', dialCode: '47', flag: '🇧🇻' },
  { name: 'Reino Unido', code: 'GB', dialCode: '44', flag: '🇬🇧' },
  { name: 'Canadá', code: 'CA', dialCode: '1', flag: '🇨🇦' },
  { name: 'Chile', code: 'CL', dialCode: '56', flag: '🇨🇱' },
  { name: 'China', code: 'CN', dialCode: '86', flag: '🇨🇳' },
  { name: 'Colômbia', code: 'CO', dialCode: '57', flag: '🇨🇴' },
  { name: 'Costa Rica', code: 'CR', dialCode: '506', flag: '🇨🇷' },
  { name: 'Croácia', code: 'HR', dialCode: '385', flag: '🇭🇷' },
  { name: 'Cuba', code: 'CU', dialCode: '53', flag: '🇨🇺' },
  { name: 'Curaçao', code: 'CW', dialCode: '599', flag: '🇨🇼' },
  { name: 'Chipre', code: 'CY', dialCode: '357', flag: '🇨🇾' },
  { name: 'República Tcheca', code: 'CZ', dialCode: '420', flag: '🇨🇿' },
  { name: 'Dinamarca', code: 'DK', dialCode: '45', flag: '🇩🇰' },
  { name: 'Djibuti', code: 'DJ', dialCode: '253', flag: '🇩🇯' },
  { name: 'Dominica', code: 'DM', dialCode: '1', flag: '🇩🇲' },
  { name: 'República Dominicana', code: 'DO', dialCode: '1', flag: '🇩🇴' },
  { name: 'Equador', code: 'EC', dialCode: '593', flag: '🇪🇨' },
  { name: 'Egito', code: 'EG', dialCode: '20', flag: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', dialCode: '503', flag: '🇸🇻' },
  { name: 'Guiné Equatorial', code: 'GQ', dialCode: '240', flag: '🇬🇶' },
  { name: 'Eritreia', code: 'ER', dialCode: '291', flag: '🇪🇷' },
  { name: 'Estônia', code: 'EE', dialCode: '372', flag: '🇪🇪' },
  { name: 'Etiópia', code: 'ET', dialCode: '251', flag: '🇪🇹' },
  { name: 'Ilhas Falkland', code: 'FK', dialCode: '500', flag: '🇫🇰' },
  { name: 'Ilhas Faroé', code: 'FO', dialCode: '298', flag: '🇫🇴' },
  { name: 'Fiji', code: 'FJ', dialCode: '679', flag: '🇫🇯' },
  { name: 'Finlândia', code: 'FI', dialCode: '358', flag: '🇫🇮' },
  { name: 'França', code: 'FR', dialCode: '33', flag: '🇫🇷' },
  { name: 'Guiana Francesa', code: 'GF', dialCode: '594', flag: '🇬🇫' },
  { name: 'Polinésia Francesa', code: 'PF', dialCode: '689', flag: '🇵🇫' },
  { name: 'Territórios Franceses do Sul', code: 'TF', dialCode: '262', flag: '🇹🇫' },
  { name: 'Gabão', code: 'GA', dialCode: '241', flag: '🇬🇦' },
  { name: 'Gâmbia', code: 'GM', dialCode: '220', flag: '🇬🇲' },
  { name: 'Geórgia', code: 'GE', dialCode: '995', flag: '🇬🇪' },
  { name: 'Alemanha', code: 'DE', dialCode: '49', flag: '🇩🇪' },
  { name: 'Gana', code: 'GH', dialCode: '233', flag: '🇬🇭' },
  { name: 'Gibraltar', code: 'GI', dialCode: '350', flag: '🇬🇮' },
  { name: 'Grécia', code: 'GR', dialCode: '30', flag: '🇬🇷' },
  { name: 'Groenlândia', code: 'GL', dialCode: '299', flag: '🇬🇱' },
  { name: 'Granada', code: 'GD', dialCode: '1', flag: '🇬🇩' },
  { name: 'Guadalupe', code: 'GP', dialCode: '590', flag: '🇬🇵' },
  { name: 'Guam', code: 'GU', dialCode: '1', flag: '🇬🇺' },
  { name: 'Guatemala', code: 'GT', dialCode: '502', flag: '🇬🇹' },
  { name: 'Guernsey', code: 'GG', dialCode: '44', flag: '🇬🇬' },
  { name: 'Guiné', code: 'GN', dialCode: '224', flag: '🇬🇳' },
  { name: 'Guiné-Bissau', code: 'GW', dialCode: '245', flag: '🇬🇼' },
  { name: 'Guiana', code: 'GY', dialCode: '592', flag: '🇬🇾' },
  { name: 'Haiti', code: 'HT', dialCode: '509', flag: '🇭🇹' },
  { name: 'Ilha Heard e Ilhas McDonald', code: 'HM', dialCode: '672', flag: '🇭🇲' },
  { name: 'Santa Sé', code: 'VA', dialCode: '39', flag: '🇻🇦' },
  { name: 'Honduras', code: 'HN', dialCode: '504', flag: '🇭🇳' },
  { name: 'Hong Kong', code: 'HK', dialCode: '852', flag: '🇭🇰' },
  { name: 'Hungria', code: 'HU', dialCode: '36', flag: '🇭🇺' },
  { name: 'Islândia', code: 'IS', dialCode: '354', flag: '🇮🇸' },
  { name: 'Índia', code: 'IN', dialCode: '91', flag: '🇮🇳' },
  { name: 'Indonésia', code: 'ID', dialCode: '62', flag: '🇮🇩' },
  { name: 'Irã', code: 'IR', dialCode: '98', flag: '🇮🇷' },
  { name: 'Iraque', code: 'IQ', dialCode: '964', flag: '🇮🇶' },
  { name: 'Irlanda', code: 'IE', dialCode: '353', flag: '🇮🇪' },
  { name: 'Ilha de Man', code: 'IM', dialCode: '44', flag: '🇮🇲' },
  { name: 'Israel', code: 'IL', dialCode: '972', flag: '🇮🇱' },
  { name: 'Itália', code: 'IT', dialCode: '39', flag: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', dialCode: '1', flag: '🇯🇲' },
  { name: 'Japão', code: 'JP', dialCode: '81', flag: '🇯🇵' },
  { name: 'Jersey', code: 'JE', dialCode: '44', flag: '🇯🇪' },
  { name: 'Jordânia', code: 'JO', dialCode: '962', flag: '🇯🇴' },
  { name: 'Cazaquistão', code: 'KZ', dialCode: '7', flag: '🇰🇿' },
  { name: 'Quênia', code: 'KE', dialCode: '254', flag: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', dialCode: '686', flag: '🇰🇮' },
  { name: 'Coreia do Norte', code: 'KP', dialCode: '850', flag: '🇰🇵' },
  { name: 'Coreia do Sul', code: 'KR', dialCode: '82', flag: '🇰🇷' },
  { name: 'Kuwait', code: 'KW', dialCode: '965', flag: '🇰🇼' },
  { name: 'Quirguistão', code: 'KG', dialCode: '996', flag: '🇰🇬' },
  { name: 'Laos', code: 'LA', dialCode: '856', flag: '🇱🇦' },
  { name: 'Letônia', code: 'LV', dialCode: '371', flag: '🇱🇻' },
  { name: 'Líbano', code: 'LB', dialCode: '961', flag: '🇱🇧' },
  { name: 'Lesoto', code: 'LS', dialCode: '266', flag: '🇱🇸' },
  { name: 'Libéria', code: 'LR', dialCode: '231', flag: '🇱🇷' },
  { name: 'Líbia', code: 'LY', dialCode: '218', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: 'LI', dialCode: '423', flag: '🇱🇮' },
  { name: 'Lituânia', code: 'LT', dialCode: '370', flag: '🇱🇹' },
  { name: 'Luxemburgo', code: 'LU', dialCode: '352', flag: '🇱🇺' },
  { name: 'Macau', code: 'MO', dialCode: '853', flag: '🇲🇴' },
  { name: 'Macedônia', code: 'MK', dialCode: '389', flag: '🇲🇰' },
  { name: 'Madagascar', code: 'MG', dialCode: '261', flag: '🇲🇬' },
  { name: 'Malawi', code: 'MW', dialCode: '265', flag: '🇲🇼' },
  { name: 'Malásia', code: 'MY', dialCode: '60', flag: '🇲🇾' },
  { name: 'Maldivas', code: 'MV', dialCode: '960', flag: '🇲🇻' },
  { name: 'Mali', code: 'ML', dialCode: '223', flag: '🇲🇱' },
  { name: 'Malta', code: 'MT', dialCode: '356', flag: '🇲🇹' },
  { name: 'Ilhas Marshall', code: 'MH', dialCode: '692', flag: '🇲🇭' },
  { name: 'Martinica', code: 'MQ', dialCode: '596', flag: '🇲🇶' },
  { name: 'Mauritânia', code: 'MR', dialCode: '222', flag: '🇲🇷' },
  { name: 'Maurício', code: 'MU', dialCode: '230', flag: '🇲🇺' },
  { name: 'Mayotte', code: 'YT', dialCode: '262', flag: '🇾🇹' },
  { name: 'México', code: 'MX', dialCode: '52', flag: '🇲🇽' },
  { name: 'Micronésia', code: 'FM', dialCode: '691', flag: '🇫🇲' },
  { name: 'Moldávia', code: 'MD', dialCode: '373', flag: '🇲🇩' },
  { name: 'Mônaco', code: 'MC', dialCode: '377', flag: '🇲🇨' },
  { name: 'Mongólia', code: 'MN', dialCode: '976', flag: '🇲🇳' },
  { name: 'Montenegro', code: 'ME', dialCode: '382', flag: '🇲🇪' },
  { name: 'Montserrat', code: 'MS', dialCode: '1', flag: '🇲🇸' },
  { name: 'Marrocos', code: 'MA', dialCode: '212', flag: '🇲🇦' },
  { name: 'Moçambique', code: 'MZ', dialCode: '258', flag: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', dialCode: '95', flag: '🇲🇲' },
  { name: 'Namíbia', code: 'NA', dialCode: '264', flag: '🇳🇦' },
  { name: 'Nauru', code: 'NR', dialCode: '674', flag: '🇳🇷' },
  { name: 'Nepal', code: 'NP', dialCode: '977', flag: '🇳🇵' },
  { name: 'Países Baixos', code: 'NL', dialCode: '31', flag: '🇳🇱' },
  { name: 'Nova Caledônia', code: 'NC', dialCode: '687', flag: '🇳🇨' },
  { name: 'Nova Zelândia', code: 'NZ', dialCode: '64', flag: '🇳🇿' },
  { name: 'Nicarágua', code: 'NI', dialCode: '505', flag: '🇳🇮' },
  { name: 'Níger', code: 'NE', dialCode: '227', flag: '🇳🇪' },
  { name: 'Nigéria', code: 'NG', dialCode: '234', flag: '🇳🇬' },
  { name: 'Niue', code: 'NU', dialCode: '683', flag: '🇳🇺' },
  { name: 'Ilha Norfolk', code: 'NF', dialCode: '672', flag: '🇳🇫' },
  { name: 'Ilhas Marianas do Norte', code: 'MP', dialCode: '1', flag: '🇲🇵' },
  { name: 'Noruega', code: 'NO', dialCode: '47', flag: '🇳🇴' },
  { name: 'Omã', code: 'OM', dialCode: '968', flag: '🇴🇲' },
  { name: 'Paquistão', code: 'PK', dialCode: '92', flag: '🇵🇰' },
  { name: 'Palau', code: 'PW', dialCode: '680', flag: '🇵🇼' },
  { name: 'Palestina', code: 'PS', dialCode: '970', flag: '🇵🇸' },
  { name: 'Panamá', code: 'PA', dialCode: '507', flag: '🇵🇦' },
  { name: 'Papua Nova Guiné', code: 'PG', dialCode: '675', flag: '🇵🇬' },
  { name: 'Paraguai', code: 'PY', dialCode: '595', flag: '🇵🇾' },
  { name: 'Peru', code: 'PE', dialCode: '51', flag: '🇵🇪' },
  { name: 'Filipinas', code: 'PH', dialCode: '63', flag: '🇵🇭' },
  { name: 'Pitcairn', code: 'PN', dialCode: '870', flag: '🇵🇳' },
  { name: 'Polônia', code: 'PL', dialCode: '48', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', dialCode: '351', flag: '🇵🇹' },
  { name: 'Porto Rico', code: 'PR', dialCode: '1', flag: '🇵🇷' },
  { name: 'Catar', code: 'QA', dialCode: '974', flag: '🇶🇦' },
  { name: 'Reunião', code: 'RE', dialCode: '262', flag: '🇷🇪' },
  { name: 'Romênia', code: 'RO', dialCode: '40', flag: '🇷🇴' },
  { name: 'Rússia', code: 'RU', dialCode: '7', flag: '🇷🇺' },
  { name: 'Ruanda', code: 'RW', dialCode: '250', flag: '🇷🇼' },
  { name: 'São Bartolomeu', code: 'BL', dialCode: '1', flag: '🇧🇱' },
  { name: 'Santa Helena', code: 'SH', dialCode: '290', flag: '🇸🇭' },
  { name: 'São Cristóvão e Nevis', code: 'KN', dialCode: '1', flag: '🇰🇳' },
  { name: 'Santa Lúcia', code: 'LC', dialCode: '1', flag: '🇱🇨' },
  { name: 'Saint Martin', code: 'MF', dialCode: '1', flag: '🇲🇫' },
  { name: 'São Pedro e Miquelão', code: 'PM', dialCode: '508', flag: '🇵🇲' },
  { name: 'São Vicente e Granadinas', code: 'VC', dialCode: '1', flag: '🇻🇨' },
  { name: 'Samoa', code: 'WS', dialCode: '685', flag: '🇼🇸' },
  { name: 'San Marino', code: 'SM', dialCode: '378', flag: '🇸🇲' },
  { name: 'São Tomé e Príncipe', code: 'ST', dialCode: '239', flag: '🇸🇹' },
  { name: 'Arábia Saudita', code: 'SA', dialCode: '966', flag: '🇸🇦' },
  { name: 'Senegal', code: 'SN', dialCode: '221', flag: '🇸🇳' },
  { name: 'Sérvia', code: 'RS', dialCode: '381', flag: '🇷🇸' },
  { name: 'Seychelles', code: 'SC', dialCode: '248', flag: '🇸🇨' },
  { name: 'Serra Leoa', code: 'SL', dialCode: '232', flag: '🇸🇱' },
  { name: 'Singapura', code: 'SG', dialCode: '65', flag: '🇸🇬' },
  { name: 'Sint Maarten', code: 'SX', dialCode: '1', flag: '🇸🇽' },
  { name: 'Eslováquia', code: 'SK', dialCode: '421', flag: '🇸🇰' },
  { name: 'Eslovênia', code: 'SI', dialCode: '386', flag: '🇸🇮' },
  { name: 'Ilhas Salomão', code: 'SB', dialCode: '677', flag: '🇸🇧' },
  { name: 'Somália', code: 'SO', dialCode: '252', flag: '🇸🇴' },
  { name: 'África do Sul', code: 'ZA', dialCode: '27', flag: '🇿🇦' },
  { name: 'Ilhas Geórgia do Sul e Sandwich do Sul', code: 'GS', dialCode: '500', flag: '🇬🇸' },
  { name: 'Espanha', code: 'ES', dialCode: '34', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', dialCode: '94', flag: '🇱🇰' },
  { name: 'Sudão', code: 'SD', dialCode: '249', flag: '🇸🇩' },
  { name: 'Suriname', code: 'SR', dialCode: '597', flag: '🇸🇷' },
  { name: 'Svalbard e Jan Mayen', code: 'SJ', dialCode: '47', flag: '🇸🇯' },
  { name: 'Suazilândia', code: 'SZ', dialCode: '268', flag: '🇸🇿' },
  { name: 'Suécia', code: 'SE', dialCode: '46', flag: '🇸🇪' },
  { name: 'Suíça', code: 'CH', dialCode: '41', flag: '🇨🇭' },
  { name: 'Taiwan', code: 'TW', dialCode: '886', flag: '🇹🇼' },
  { name: 'Tajiquistão', code: 'TJ', dialCode: '992', flag: '🇹🇯' },
  { name: 'Tanzânia', code: 'TZ', dialCode: '255', flag: '🇹🇿' },
  { name: 'Tailândia', code: 'TH', dialCode: '66', flag: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TL', dialCode: '670', flag: '🇹🇱' },
  { name: 'Togo', code: 'TG', dialCode: '228', flag: '🇹🇬' },
  { name: 'Tokelau', code: 'TK', dialCode: '690', flag: '🇹🇰' },
  { name: 'Tonga', code: 'TO', dialCode: '676', flag: '🇹🇴' },
  { name: 'Trinidad e Tobago', code: 'TT', dialCode: '1', flag: '🇹🇹' },
  { name: 'Tunísia', code: 'TN', dialCode: '216', flag: '🇹🇳' },
  { name: 'Turquia', code: 'TR', dialCode: '90', flag: '🇹🇷' },
  { name: 'Turcomenistão', code: 'TM', dialCode: '993', flag: '🇹🇲' },
  { name: 'Ilhas Turcas e Caicos', code: 'TC', dialCode: '1', flag: '🇹🇨' },
  { name: 'Tuvalu', code: 'TV', dialCode: '688', flag: '🇹🇻' },
  { name: 'Uganda', code: 'UG', dialCode: '256', flag: '🇺🇬' },
  { name: 'Ucrânia', code: 'UA', dialCode: '380', flag: '🇺🇦' },
  { name: 'Emirados Árabes Unidos', code: 'AE', dialCode: '971', flag: '🇦🇪' },
  { name: 'Estados Unidos', code: 'US', dialCode: '1', flag: '🇺🇸' },
  { name: 'Uruguai', code: 'UY', dialCode: '598', flag: '🇺🇾' },
  { name: 'Uzbequistão', code: 'UZ', dialCode: '998', flag: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', dialCode: '678', flag: '🇻🇺' },
  { name: 'Venezuela', code: 'VE', dialCode: '58', flag: '🇻🇪' },
  { name: 'Vietnã', code: 'VN', dialCode: '84', flag: '🇻🇳' },
  { name: 'Ilhas Virgens Britânicas', code: 'VG', dialCode: '1', flag: '🇻🇬' },
  { name: 'Ilhas Virgens Americanas', code: 'VI', dialCode: '1', flag: '🇻🇮' },
  { name: 'Wallis e Futuna', code: 'WF', dialCode: '681', flag: '🇼🇫' },
  { name: 'Saara Ocidental', code: 'EH', dialCode: '212', flag: '🇪🇭' },
  { name: 'Iêmen', code: 'YE', dialCode: '967', flag: '🇾🇪' },
  { name: 'Zâmbia', code: 'ZM', dialCode: '260', flag: '🇿🇲' },
  { name: 'Zimbábue', code: 'ZW', dialCode: '263', flag: '🇿🇼' },
];

export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code || country.dialCode === code);
};

export const getCountryByDialCode = (dialCode: string): Country | undefined => {
  return countries.find(country => country.dialCode === dialCode);
};

export const defaultCountry: Country = countries[0]; // Brasil

